/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inteface;

import ClassPartager.UnClient;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.Timer;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.MinimalBalloonStyle;
import net.java.balloontip.utils.FadingUtils;

/**
 *
 * @author Selwyn
 */
public class Bienvenue extends javax.swing.JDialog {

    public int ok;
    public UnClient client;
    BalloonTip myBalloonTip;
    public String login;
    public String motDePass;

    /**
     * Creates new form Bienvenue
     *
     * @param parent
     * @param modal
     */
    public Bienvenue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private ActionListener onStop = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            myBalloonTip.setEnabled(true);
        }
    };
    Timer timer = new Timer(3000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            FadingUtils.fadeOutBalloon(myBalloonTip, onStop, 500, 24);
        }
    });

    private void bulleErreur(String erreur, JComponent cmp) {
        JLabel err = new JLabel();
        Font font = new Font("Segoe UI Semibold", 1, 14);
        err.setFont(font);
        err.setText(erreur);
        err.setForeground(Color.yellow);
        myBalloonTip = new BalloonTip(cmp, null);
        myBalloonTip.setContents(err);
        myBalloonTip.setStyle(new MinimalBalloonStyle(Color.darkGray, 8));
        myBalloonTip.setCloseButton(null);
        FadingUtils.fadeInBalloon(myBalloonTip, onStop, 300, 24);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parBut = new javax.swing.JLabel();
        conIdentifiant = new javax.swing.JTextField();
        conPassword = new javax.swing.JPasswordField();
        identifiant = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        password2 = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        courriel = new javax.swing.JTextField();
        dossier = new javax.swing.JTextField();
        connectBut = new javax.swing.JLabel();
        engBut = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/parBut.png"))); // NOI18N
        parBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                parButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                parButMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                parButMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                parButMouseReleased(evt);
            }
        });
        getContentPane().add(parBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 40, 37));

        conIdentifiant.setBackground(new java.awt.Color(51, 51, 51));
        conIdentifiant.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        conIdentifiant.setForeground(new java.awt.Color(255, 255, 255));
        conIdentifiant.setBorder(null);
        conIdentifiant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        conIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conIdentifiantActionPerformed(evt);
            }
        });
        getContentPane().add(conIdentifiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 246, 36));

        conPassword.setBackground(new java.awt.Color(51, 51, 51));
        conPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        conPassword.setForeground(new java.awt.Color(255, 255, 255));
        conPassword.setBorder(null);
        getContentPane().add(conPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 246, 36));

        identifiant.setBackground(new java.awt.Color(51, 51, 51));
        identifiant.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        identifiant.setForeground(new java.awt.Color(255, 255, 255));
        identifiant.setBorder(null);
        getContentPane().add(identifiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 50, 246, 36));

        nom.setBackground(new java.awt.Color(51, 51, 51));
        nom.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setBorder(null);
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 125, 246, 36));

        prenom.setBackground(new java.awt.Color(51, 51, 51));
        prenom.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.setBorder(null);
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 203, 246, 36));

        password2.setBackground(new java.awt.Color(51, 51, 51));
        password2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 255, 255));
        password2.setBorder(null);
        password2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                password2FocusLost(evt);
            }
        });
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 356, 246, 36));

        password.setBackground(new java.awt.Color(51, 51, 51));
        password.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 278, 246, 36));

        courriel.setBackground(new java.awt.Color(51, 51, 51));
        courriel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        courriel.setForeground(new java.awt.Color(255, 255, 255));
        courriel.setBorder(null);
        courriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courrielActionPerformed(evt);
            }
        });
        getContentPane().add(courriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 434, 246, 36));

        dossier.setBackground(new java.awt.Color(51, 51, 51));
        dossier.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        dossier.setForeground(new java.awt.Color(255, 255, 255));
        dossier.setBorder(null);
        getContentPane().add(dossier, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 510, 210, 36));

        connectBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ConBut2.png"))); // NOI18N
        connectBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                connectButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                connectButMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connectButMousePressed(evt);
            }
        });
        getContentPane().add(connectBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        engBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/engBut.png"))); // NOI18N
        engBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                engButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                engButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                engButMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                engButMousePressed(evt);
            }
        });
        getContentPane().add(engBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/welcome.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void connectButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButMouseEntered
        connectBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/conBut2Hover.png")));
    }//GEN-LAST:event_connectButMouseEntered

    private void connectButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButMouseExited
        connectBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/conBut2.png")));
    }//GEN-LAST:event_connectButMouseExited

    private void connectButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButMouseClicked
        if (this.conIdentifiant.getText().isEmpty()) {
            bulleErreur("Entrez votre identifiant", this.conIdentifiant);
            this.conIdentifiant.requestFocus();
            timer.setRepeats(false);
            timer.start();
        } else if (this.conPassword.getText().isEmpty()) {
            bulleErreur("Entrez votre identifiant", this.conPassword);
            this.conPassword.requestFocus();
            timer.setRepeats(false);
            timer.start();
        } else {
            this.login = this.conIdentifiant.getText();
            this.motDePass = this.conPassword.getText();
            ok = 1;
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_connectButMouseClicked

    private void connectButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButMousePressed
        connectBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/conBut2Click.png")));
    }//GEN-LAST:event_connectButMousePressed

    private void engButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_engButMouseEntered
        engBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/engButHover.png")));
    }//GEN-LAST:event_engButMouseEntered

    private void engButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_engButMouseExited
        engBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/engBut.png")));
    }//GEN-LAST:event_engButMouseExited

    private void engButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_engButMousePressed
        engBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/engButClick.png")));
    }//GEN-LAST:event_engButMousePressed

    private void parButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parButMouseEntered
        parBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/parButHover.png")));
    }//GEN-LAST:event_parButMouseEntered

    private void parButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parButMouseExited
        parBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/parBut.png")));
    }//GEN-LAST:event_parButMouseExited

    private void parButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parButMousePressed
        parBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/parButClick.png")));
    }//GEN-LAST:event_parButMousePressed

    private void parButMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parButMouseReleased
        parBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/parButHover.png")));
    }//GEN-LAST:event_parButMouseReleased

    private void parButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parButMouseClicked
        JFileChooser chooser;
        chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                dossier.setText(chooser.getSelectedFile().getCanonicalPath());
            } catch (IOException ex) { }
        } else {
            dossier.setText("Choisir un dossier");
        }
    }//GEN-LAST:event_parButMouseClicked

    private void courrielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courrielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courrielActionPerformed


    private void password2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password2FocusLost
        if (!password.getText().equals(password2.getText())) {
            bulleErreur("Les mots de passe ne correpondent pas", this.password);
            password.requestFocus();
        }
    }//GEN-LAST:event_password2FocusLost

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        password2.setText(null);
    }//GEN-LAST:event_passwordKeyTyped

    private void engButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_engButMouseClicked
        if (this.identifiant.getText().isEmpty()) {
            bulleErreur("Entrez votre identifiant", this.identifiant);
            this.identifiant.requestFocus();
            timer.setRepeats(false);
            timer.start();
        } else if (this.nom.getText().isEmpty()) {
            bulleErreur("Entrez votre nom", this.nom);
            this.nom.requestFocus();
            timer.setRepeats(false);
            timer.start();
        } else if (this.prenom.getText().isEmpty()) {
            bulleErreur("Entrez votre prenom", this.prenom);
            this.prenom.requestFocus();
            timer.setRepeats(false);
            timer.start();
        } else if (this.password.getText().isEmpty()) {
            bulleErreur("Entrez votre votre mot de passe", this.password);
            this.password.requestFocus();
            timer.setRepeats(false);
            timer.start();
        } else if (!password.getText().equals(password2.getText())) {
            this.password2FocusLost(null);
        } else if (this.dossier.getText().isEmpty() || this.dossier.getText().equals("Choisir un dossier")) {
            this.parButMouseClicked(evt);
        } else {
            client = new UnClient(identifiant.getText(), password2.getText(), nom.getText(), prenom.getText(), courriel.getText(), dossier.getText());
            ok = 2;
            setVisible(false);
            dispose();
        }


    }//GEN-LAST:event_engButMouseClicked

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost

    }//GEN-LAST:event_passwordFocusLost

    private void conIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conIdentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conIdentifiantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Bienvenue dialog = new Bienvenue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField conIdentifiant;
    private javax.swing.JPasswordField conPassword;
    private javax.swing.JLabel connectBut;
    private javax.swing.JTextField courriel;
    private javax.swing.JTextField dossier;
    private javax.swing.JLabel engBut;
    private javax.swing.JTextField identifiant;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel parBut;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}
